title = "Mix of concurrent and sequential test"
tickers = [ "AAPL", "ACME" ] 

accounts = { alice = ["ACME", "AAPL"], bob = ["ACME", "AAPL"], carol = ["ACME"]}

[transactions.sequential]
normal = "AA"

[outcomes]
time = 100 

[outcomes.accounts]
alice = {ACME = 0, AAPL = 50}
bob   = {ACME = 10, AAPL = 5}
carol = {ACME = 40}