[package]
name = "cryptography"
version = "0.1.0"
authors = [ "Jesse Lancaster <jesse@polymath.network>",
            "Parnian Alimi   <parnian@polymath.network>",
          ]
readme = "README.md"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "The Repository for cryptographic libraries used in Polymesh"
edition = "2018"
exclude = [ ".gitignore",
          ]

[dependencies]
# schnorrkel's latest stable version uses an older version of Dalek.
curve25519-dalek = { version = "1.2", default-features = false }
bulletproofs = { version = "2.0", default-features = false }
sha3 = { version = "0.8", default-features = false }
rand = { version = "0.7.3", default-features = false, optional = true }
rand_core = { version = "0.5.1", default-features = false }
getrandom = { version = "0.1.14", default-features = false, optional = true }
serde = { version = "1.0.104", default-features = false, optional = true }
schnorrkel = { version = "0.8.5", features = ["u64_backend"], default-features = false, optional = true }


[dev-dependencies]
rand = "0.7.3"

[features]
default = ["std", "rand", "getrandom"]
std = ["rand", "rand/std", "schnorrkel/std", ]
nightly = ["curve25519-dalek/nightly", ]

[[example]]
# Use `cargo +nightly build --example simple` to compile this example.
name = "simple"
path = "src/examples/simple.rs"

