[workspace]

members = [
	"cryptography",
	"cli/agui/common",
	"cli/agui/scp",
	"cli/agui/scv",
	"cli/mercat/account",
	"cli/mercat/chain_setup",
	"cli/mercat/common",
	"cli/mercat/mediator",
	"cli/mercat/validator",
]
