version: 2
jobs:
  lint:
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: ./scripts/docker.sh build
      - run:
          name: Check formatting
          command: ./scripts/docker.sh run ./scripts/lint
  build:
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: ./scripts/docker.sh build
      - run:
          name: Store rust version in an environment var for cache key
          command: ./scripts/docker.sh run rustc --version > rust.version
      - restore_cache:
          keys:
            - v2-nightly-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
            - v2-nightly-cache-{{ checksum "./rust.version" }}
            - v2-cli-cache-{{ checksum "./rust.version" }}
      - run:
          name: Build nightly
          command: ./scripts/docker.sh run cargo +nightly build
          no_output_timeout: 4h
      - save_cache:
          key: v2-nightly-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
  test:
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: ./scripts/docker.sh build
      - run:
          name: Store rust version in a file for cache key
          command: ./scripts/docker.sh run rustc --version > rust.version
      - restore_cache:
          keys:
            - v6-test-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
            - v6-test-cache-{{ checksum "./rust.version" }}
      - run:
          name: Run tests
          command: >-
            # ----------------------------------- Test Rust &&
            ./scripts/docker.sh run RUST_LOG=info cargo +nightly test &&

            # ----------------------------------- Test WASM &&
            cd confidential-identity/wasm &&
            rustup run nightly wasm-pack build --target nodejs &&

            cd examples &&
            npm install &&
            npm run test &&

            cd ../../../private-identity-audit/wasm  &&
            rustup run nightly wasm-pack build --target nodejs &&

            cd examples &&
            npm install &&
            npm run test

            # ----------------------------------- Test FFI &&
            cd ../../ffi/ &&
            make build &&
            make run &&

            cd ../../confidential-identity/ffi/ &&
            make build &&
            make run
            
          no_output_timeout: 30m
      - save_cache:
          key: v6-test-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
  build_wasm:
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: ./scripts/docker.sh build
      - run:
          name: Store rust version in a file for cache key
          command: ./scripts/docker.sh run rustc --version > rust.version
      - restore_cache:
          keys:
            - v6-test-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
            - v6-test-cache-{{ checksum "./rust.version" }}
      - run:
          name: Run tests
          command: >-
            ./scripts/docker.sh run cd cryptography-core &&
            echo "Wasm build (features 'no_std' & 'u32_backend')"  &&
            cargo +nightly build --target wasm32-unknown-unknown --bench elgamal_decryption &&
            cargo +nightly build --target wasm32-unknown-unknown --no-default-features --features no_std --features u32_backend &&

            cd ../mercat &&
            echo "Wasm build (features 'no_std' & 'u32_backend')"  &&
            cargo +nightly build --target wasm32-unknown-unknown --bench mercat_account &&
            cargo +nightly build --target wasm32-unknown-unknown --bench mercat_asset &&
            cargo +nightly build --target wasm32-unknown-unknown --bench mercat_transaction &&
            cargo +nightly build --target wasm32-unknown-unknown --no-default-features --features no_std --features u32_backend

          no_output_timeout: 30m
      - save_cache:
          key: v6-test-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
  bench:
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: ./scripts/docker.sh build
      - run:
          name: Store rust version in a file for cache key
          command: ./scripts/docker.sh run rustc --version > rust.version
      - restore_cache:
          keys:
            - v6-bench-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
            - v6-bench-cache-{{ checksum "./rust.version" }}
      - run:
          name: Run benchmarks
          command: ./scripts/docker.sh run cargo +nightly bench
          no_output_timeout: 30m
      - save_cache:
          key: v6-bench-cache-{{ checksum "./rust.version" }}-{{ checksum "./Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - develop
                - master
  benchmark:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
                - master
    jobs:
      - bench
