version: 2
jobs:
  lint:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Check formatting
          command: ./scripts/lint
  build:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Store rust version in an environment var for cache key
          command: rustc --version > rust.version
      - run:
          name: Build nightly
          command: cargo +nightly build
          no_output_timeout: 4h
  test:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Store rust version in a file for cache key
          command: rustc --version > rust.version
      - run:
          name: Run tests
          command: >-
            cargo +nightly test &&
            cargo +nightly build --bench elgamal_decryption &&
            echo "TODO: add wasm tests"
          no_output_timeout: 30m
  bench:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Store rust version in a file for cache key
          command: rustc --version > rust.version
      - run:
          name: Run tests
          command: cargo +nightly bench
          no_output_timeout: 30m
workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - develop
                - master
  benchmark:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
                - master
    jobs:
      - bench