[package]
name = "mercat-chain-setup"
version = "0.1.0"
authors = [ "Polymath Inc" ]
edition = "2018"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "MERCAT CLI for preping the data on the \"chain\" for a successful run of other MERCAT CLIs"

[dependencies]
cryptography = { path = "../../../cryptography/" }
mercat_common = { package = "mercat-common", path = "../common/" }

serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"]}
log = { version = "0.4.8"}
env_logger = { version = "0.7.1" }
confy = { version = "0.4.0" }
structopt = { version = "0.3", default-features = false }
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }
base64 = { version = "0.12.1" }
failure = { version = "0.1.7" }

# Crypto
rand = { version = "0.7.3", features = ["wasm-bindgen", "getrandom", "alloc"], default-features = false }
curve25519-dalek = { git = "https://github.com/PolymathNetwork/curve25519-dalek.git", branch = "v2-packed-simd", default-features = false, features = ["nightly", "u64_backend", "alloc", "serde"] }
schnorrkel = { git = "https://github.com/PolymathNetwork/schnorrkel.git", branch = "fix-simd-issue", default-features = false }
