[package]
name = "mercat-common"
version = "0.1.0"
authors = [ "Jesse Lancaster <jesse@polymath.network>",
            "Arash Afshar    <arash@polymath.network>",
            "Parnian Alimi   <parnian@polymath.network>",
          ]
edition = "2018"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "MERCAT CLI common library"

[dependencies]
cryptography = { package = "cryptography", path = "../../../cryptography/" }

serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"]}
log = { version = "0.4.8"}
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }

# Crypto
rand = { version = "0.7.3", features = ["wasm-bindgen", "getrandom", "alloc"], default-features = false }
curve25519-dalek = { version = "2.0.0", features = ["u64_backend", "alloc", "serde"], default-features = false }
