name: Upload Mercat Release Asset

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Upload Mercat Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # -------------- Proceed only if Cargo.toml file is modified
      - uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            mercat/Cargo.toml

      - name: Check if the version has been changed
        if: env.GIT_DIFF
        run: bash ./scripts/rust-version-changed.sh mercat
        env:
          PREV_SHA: ${{ github.event.before }}

      - name: Build project and create the artifacts
        if: env.VERSION_CHANGED
        run: bash ./scripts/mercat-artifacts.sh

      # -------------- Create a tag
      - name: Get tag name
        id: get-tag-name
        if: env.VERSION_CHANGED
        run: bash ./scripts/get-tag-name.sh mercat
      - name: Bump version and push tag
        id: tag-version
        if: env.TAG_NAME
        uses: mathieudutour/github-tag-action@v5.1

      # -------------- Create a release from the tag
      - name: Create Release
        if: env.VERSION_CHANGED
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      # -------------- Attach the artifacts to the release
      - name: Upload MERCAT Source
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-src
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/mercat-src.tar.gz
          asset_name: ${{ env.TAG_NAME }}-src.tar.gz
          asset_content_type: application/zip
      - name: Upload MERCAT Source Checksum
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-src-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/mercat-src.sha256sum
          asset_name: ${{ env.TAG_NAME }}-src.sha256sum
          asset_content_type: text/plain

      - name: Upload MERCAT CLI
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/mercat-linux-x64.tar.gz 
          asset_name: ${{ env.TAG_NAME }}-linux-x64.tar.gz
          asset_content_type: application/zip
      - name: Upload MERCAT CLI checksum
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-cli-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/mercat-linux-x64.sha256sum
          asset_name: ${{ env.TAG_NAME }}-linux-x64.sha256sum
          asset_content_type: text/plain

      - name: Upload MERCAT NPM
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-npm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/mercat-npm.tar.gz
          asset_name: ${{ env.TAG_NAME }}-npm.tar.gz
          asset_content_type: application/zip
      - name: Upload MERCAT NPM Checksum
        if: env.VERSION_CHANGED
        id: upload-release-asset-mercat-npm-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/mercat-npm.sha256sum
          asset_name: ${{ env.TAG_NAME }}-npm.sha256sum
          asset_content_type: text/plain

      # -------------- Publish the npm artifacts to npmjs
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd mercat/wasm/pkg/ && npm publish --access public
        if: env.VERSION_CHANGED
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
